// Charts: hand-drawn axes, real numbers. The data below is generated by a seeded
// process and labelled as illustration; swap in real data and keep the drawing code.
function lcg(seed) { let s = seed; return () => (s = (s * 1664525 + 1013904223) % 4294967296) / 4294967296; }

export default [
  {
    id: 'chart-progress', cat: 'chart', w: 760, h: 420, seed: 61, motion: true,
    title: { zh: '实验进度 · 灰点丢掉,绿点留下', en: 'Experiments · grey dropped, green kept' },
    desc: { zh: '每个点是一次实验。比当前最好还低就留下(绿),否则丢掉(灰);绿色台阶线是「目前最好」。数据是示意。', en: 'Each dot is one run. Lower than the best so far: kept (green); otherwise dropped (grey). The green steps are the best so far. Illustrative data.' },
    draw(S, P) {
      // A run improves on the best so far about a quarter of the time (seed 7: 11 of 47),
      // by less and less. Higher score = higher on the page; the y range comes from the data.
      const r = lcg(7), N = 48, X = i => 90 + i * 13.2;
      let best = 0.998; const pts = [];
      for (let i = 0; i < N; i++) {
        const v = i === 0 ? best : best + (r() - 0.24) * 0.0042 * Math.exp(-i / 60);
        const keep = i > 0 && v < best; if (keep) best = v;
        pts.push({ i, v, keep, best });
      }
      const hiV = Math.max(...pts.map(p => p.v)), loV = Math.min(...pts.map(p => p.v));
      const Y = v => 80 + (hiV - v) / (hiV - loV) * 230;
      S.at(0, 1.2, () => {
        S.arrow([[80, 340], [80, 50]], { w: 't', head: 8 });
        S.arrow([[80, 340], [730, 340]], { w: 't', head: 8 });
        P.say(S, 92, 58, { zh: '分数(越低越好)', en: 'score (lower is better)' }, { size: 15, ink: '2' });
        P.say(S, 724, 366, { zh: '第几次实验', en: 'run #' }, { anchor: 'end', size: 15, ink: '2' });
        [hiV, (hiV + loV) / 2, loV].map(v => Math.round(v * 1000) / 1000).forEach(v => { S.line(74, Y(v), 80, Y(v), { w: 'h', double: false }); P.say(S, 68, Y(v) + 5, v.toFixed(3), { anchor: 'end', size: 13, font: 'mono', ink: '2' }); });
      });
      S.at(1, 3.2, () => pts.forEach(p => S.dot(X(p.i), Y(p.v), p.keep || p.i === 0 ? 5 : 3.6, { pen: p.keep || p.i === 0 ? 'green' : 'grey' })));
      const step = []; pts.forEach((p, k) => { if (k) step.push([X(p.i), Y(pts[k - 1].best)]); step.push([X(p.i), Y(p.best)]); });
      S.at(4, 2, () => S.path(step, { pen: 'green', smooth: false, w: 't' }));
      const last = pts.filter(p => p.keep).pop();
      S.at(6, 1, () => { S.ring(X(last.i), Y(last.v), 18, 16, {}); P.say(S, X(last.i) - 26, Y(last.v) - 24, { zh: '目前最好 ' + last.v.toFixed(4), en: 'best so far ' + last.v.toFixed(4) }, { anchor: 'end', size: 16, ink: 'green' }); });
      const kept = pts.filter(p => p.keep).length + 1;   // + the first run, the baseline
      S.at(6.4, 0.6, () => P.say(S, 720, 400, { zh: `${N} 次实验 · 留下 ${kept} 次(含第一次基线,示意数据)`, en: `${N} runs · ${kept} kept incl. the baseline (illustrative)` }, { anchor: 'end', size: 14, ink: '2' }));
    },
  },
  {
    id: 'chart-bars', cat: 'chart', w: 760, h: 400, seed: 63, motion: true,
    title: { zh: '柱状图 · 改之前和改之后', en: 'Bar chart · before and after' },
    desc: { zh: '同一件事改前改后各量一次。柱子用彩铅涂,数值写在柱顶,差多少用一根手画箭头标出来。数据是示意。', en: 'The same thing measured before and after a change. Coloured-pencil bars, the value on top, the difference marked with a hand-drawn arrow. Illustrative data.' },
    draw(S, P) {
      const rows = [{ zh: '冷启动', en: 'cold start', a: 9.6, b: 3.1 }, { zh: '增量编译', en: 'incremental', a: 4.2, b: 1.6 }, { zh: '跑测试', en: 'tests', a: 6.8, b: 5.9 }];
      const base = 330, Hs = 26, bw = 54;
      S.at(0, 1, () => { S.line(70, base, 720, base, { w: 't' }); P.say(S, 70, 50, { zh: '耗时(分钟,示意)', en: 'minutes (illustrative)' }, { size: 15, ink: '2' }); });
      rows.forEach((r, k) => {
        const x = 110 + k * 210;
        S.at(1 + k * 0.9, 1.2, () => {
          S.rect(x, base - r.a * Hs, bw, r.a * Hs, { fill: 'grey', gap: 4.6 });
          S.rect(x + bw + 14, base - r.b * Hs, bw, r.b * Hs, { fill: 'orange', gap: 4.6 });
          P.say(S, x + bw / 2, base - r.a * Hs - 10, r.a.toFixed(1), { anchor: 'middle', size: 16, font: 'mono' });
          P.say(S, x + bw * 1.5 + 14, base - r.b * Hs - 10, r.b.toFixed(1), { anchor: 'middle', size: 16, font: 'mono', ink: 'orange' });
          P.say(S, x + bw + 7, base + 30, { zh: r.zh, en: r.en }, { anchor: 'middle', size: 17 });
        });
      });
      const k0 = rows[0], ratio = (k0.a / k0.b).toFixed(1);
      S.at(4, 1.2, () => {
        S.arrow([[300, 118], [262, 150], [244, 228]], { w: 't', pen: 'orange' });
        P.say(S, 310, 116, { zh: `${k0.zh}快了 ${ratio} 倍`, en: `${k0.en}: ${ratio}× faster` }, { size: 20, ink: 'orange' });
      });
      S.at(4.6, 0.6, () => {
        S.rect(520, 66, 18, 14, { fill: 'grey', style: 'wash', w: 'h' }); P.say(S, 546, 79, { zh: '改之前', en: 'before' }, { size: 15 });
        S.rect(620, 66, 18, 14, { fill: 'orange', style: 'wash', w: 'h' }); P.say(S, 646, 79, { zh: '改之后', en: 'after' }, { size: 15 });
      });
    },
  },
];
